var GAME_LEVELS = [
["                                                                           ",
 "  x                                                                       x",
 "  x                                                y                      x",
 "  x                                      y         y         y            x",
 "  x                                        y       y       y              x",
 "  x o  xx                                    y   yyyyy   y                x",
 "  x                                            y       y                  x",
 "  x o      xxx         o                y y y y    o    y y y y           x",
 "  x              xxxxx                                                    x",
 "  x o                                          xxx!!!xxx    xxx           x",
 "  x                     xx                       x!!!x                    x",
 "  x o                                            xx!xx            xxx     x",
 "  x              o          xxx                   xxx                     x",
 "  x                                                x                      x",
 "  x o            xxx                                         xxx          x",
 "  x                  o           x                                        x",
 "  x                                                                       x",
 "  x              xxxxx    xxx                                     xxx    ox",
 "  x                                                                       x",
 "  x              o              x                                        xx",
 "  x          xxxx                             o   ======   o            xxx",
 "  x  @       xxxx                                                      xxxx",
 "  xxxxxxxxxxxxxxxxxxxxxxxxx         xxxxxxxxx   xxxxxxxxxx   xxxxxxxxxxxxxx",
 "      x                             x       x   x        x   x             ",
 "      x                          xxxx       x   x        x   x             ",
 "      xk     ==                  x          x   x        x   x             ",
 "      x              =        xxxx          x   x        x   x             ",
 "      x                       x             x!!!x        x!!!x             ",
 "      xxxx   xx   xxxxxx  xxxxx             x!!!x        x!!!x             ",
 "         x!!!xx!!!x    x!!xx                xxxxx        xxxxx             ",
 "         xxxxxxxxxx    xxxxx                                               ",
 "                                                                           "],
["x                                    k                                       x    ",
 "x                                                                            x    ",
 "x                              xx                                    xxxxxxxxx    ",
 "x                                                                    x            ",
 "xxxxxx                   xx                                     xxxxx             ",
 "     x    =====                                                 x                 ",
 "     x              xx                                y     xxxxx                 ",
 "     xxxxxxx      =====                         y     y     x                     ",
 "           x                                       y  yxxxxxxxxxxxxxxxxxxxxxxxxxxx",
 "           x                                          y=       o     =     o      ",
 "           xxxxxxx                              y y y y=                         x",
 "                 x      o       o       o       o              =     o     =  xxxx",
 "                 x     xxxx            xxxx            xxxxxxxxxxxxxxxxxxxxxxxx   ",
 "                 x     xxxx   ==xx==   xxxx   ==xx==   x                          ",
 "                 x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                          ",
 "                 x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                          ",
 "                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                          "],
 ["x                                         x      y         y          y   x",
  "x                                         x         y      y       y     x",
  "x                                         x            yyyyyyyyyy             x",
  "x                                         x      xxx                o     x",
  "x                                         x                               x",
  "x                             o           x  xx                           x",
  "x                    o                    x           yyy      yyy         x",
  "x                 o                       x      xx        x         xxx  x",
  "x              o      =xxx                x                              x",
  "x                      xxx    xx   o      x                      xx       x",
  "x           xxxxx      xxx                x                      xx       x",
  "x          =x   x      xxx             o                  xx     xx       x",
  "x       xxxxx   x      xxx            =xxxx=              xx     xx       x",
  "x     ==x       x      xxx                x        xx     xx     xx       x",
  "x   xxxxx       x      xxx    k           x        xx     xx     xx       x",
  "x   x           x      xxx    xx          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "xxxxx           x!!!!!!xxx!!!!!!!!!!!!!!!!                                "],
  ["                                                                          ",
   "     =                                                  x  x  x    =      ",
   "       x   x    xxx    x  x     x   x   x   x   xxxx    x  x  x           ",
   "   =   xxxxx   x   x   x  x      x x x x    x   x  x    x  x  x       =   ",
   "           x    xxx    xxxx       x   x     x   x  x                      ",
   "     =   xxx                                            x  x  x    =      ",
   "                                                                          ",
   "xxxxxxxxxx!!!!x!!!xxx!!!!xxxxxxxx!!!!xxxx!xx!!!!xxxx!xx!xx!xxxxxxxxxxxxxxx"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
